# Generated by Django 5.2.3 on 2025-07-02 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('prep', 'Pre-production'), ('shoot', 'Principal Photography'), ('post', 'Post-production'), ('wrap', 'Wrapped')], default='prep', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('script_version', models.CharField(default='1.0', max_length=20)),
                ('script_file', models.FileField(blank=True, null=True, upload_to='scripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='production.production')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.CharField(max_length=10)),
                ('script_page', models.CharField(blank=True, max_length=10)),
                ('int_ext', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior')], max_length=3)),
                ('location_detail', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('DAWN', 'Dawn'), ('DUSK', 'Dusk'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=10)),
                ('estimated_pages', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('not_shot', 'Not Shot'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('pickup', 'Pickup Required')], default='not_shot', max_length=15)),
                ('characters', models.ManyToManyField(blank=True, to='crew.character')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='production.location')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='production.production')),
            ],
            options={
                'ordering': ['scene_number'],
                'unique_together': {('production', 'scene_number')},
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_number', models.CharField(max_length=10)),
                ('shot_type', models.CharField(choices=[('MASTER', 'Master Shot'), ('CU', 'Close Up'), ('MCU', 'Medium Close Up'), ('MS', 'Medium Shot'), ('WS', 'Wide Shot'), ('OTS', 'Over The Shoulder'), ('POV', 'Point of View'), ('INSERT', 'Insert')], max_length=10)),
                ('description', models.TextField()),
                ('camera_notes', models.TextField(blank=True)),
                ('lens', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('setup', 'Setting Up'), ('rehearsal', 'Rehearsal'), ('rolling', 'Rolling'), ('cut', 'Cut'), ('moving_on', 'Moving On'), ('completed', 'Completed')], default='setup', max_length=15)),
                ('takes_planned', models.IntegerField(default=1)),
                ('takes_completed', models.IntegerField(default=0)),
                ('takes_good', models.IntegerField(default=0)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('actual_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='production.scene')),
            ],
            options={
                'ordering': ['shot_number'],
                'unique_together': {('scene', 'shot_number')},
            },
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_number', models.IntegerField()),
                ('result', models.CharField(choices=[('good', 'Good'), ('ng', 'No Good'), ('maybe', 'Maybe'), ('print', 'Print')], max_length=10)),
                ('director_notes', models.TextField(blank=True)),
                ('script_supervisor_notes', models.TextField(blank=True)),
                ('timecode_in', models.TimeField(blank=True, null=True)),
                ('timecode_out', models.TimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='production.shot')),
            ],
            options={
                'ordering': ['take_number'],
                'unique_together': {('shot', 'take_number')},
            },
        ),
    ]
