# Generated by Django 5.2.4 on 2025-07-09
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='location_primary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='production',
            name='director',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='production',
            name='producer',
            field=models.CharField(default='TBD', max_length=100),
        ),
    ]
