# Generated by Django 5.2.4 on 2025-07-07 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_supporting', models.BooleanField(default=False)),
                ('is_background', models.BooleanField(default=False)),
                ('total_scenes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('guaranteed_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('can_view_schedule', models.BooleanField(default=True)),
                ('can_view_script', models.BooleanField(default=False)),
                ('can_view_budget', models.BooleanField(default=False)),
                ('is_department_head', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['production', 'position__department', 'position'],
            },
        ),
        migrations.CreateModel(
            name='CrewCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.TimeField()),
                ('wrap_time', models.TimeField(blank=True, null=True)),
                ('meal_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('on_call', 'On Call'), ('weather_cover', 'Weather Cover'), ('day_off', 'Day Off'), ('travel', 'Travel Day')], default='working', max_length=20)),
                ('report_to', models.CharField(default='Base Camp', max_length=100)),
                ('transport_provided', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['call_time', 'crew_member__last_name'],
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_primary', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_secondary', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('union_member', models.BooleanField(default=False)),
                ('union_number', models.CharField(blank=True, max_length=50)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('has_vehicle', models.BooleanField(default=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('shirt_size', models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2XL'), ('XXXL', '3XL')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('unavailable', 'Unavailable'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('hod', 'Head of Department'), ('key', 'Key'), ('assistant', 'Assistant'), ('trainee', 'Trainee'), ('other', 'Other')], default='other', max_length=20)),
                ('daily_rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('daily_rate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('requires_certification', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['department', 'level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shooting_day', models.IntegerField()),
                ('date', models.DateField()),
                ('general_call_time', models.TimeField()),
                ('shooting_call', models.TimeField()),
                ('wrap_time', models.TimeField(blank=True, null=True)),
                ('base_camp_location', models.TextField()),
                ('nearest_hospital', models.TextField()),
                ('parking_instructions', models.TextField(blank=True)),
                ('schedule_notes', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('weather_forecast', models.CharField(blank=True, max_length=200)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('revised', 'Revised')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
