# Generated by Django 5.2.3 on 2025-07-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='production.production'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='production.production'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewavailability',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='crew.crewmember'),
        ),
        migrations.AddField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role_level': 'talent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.crewmember'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.department'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.crewmember'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='production.production'),
        ),
        migrations.AlterUniqueTogether(
            name='crewavailability',
            unique_together={('crew_member', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('production', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='crewmember',
            unique_together={('production', 'email')},
        ),
    ]
