# Generated by Django 5.2.4 on 2025-07-07 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sheets', to='production.production'),
        ),
        migrations.AddField(
            model_name='character',
            name='first_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.scene'),
        ),
        migrations.AddField(
            model_name='character',
            name='last_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='production.scene'),
        ),
        migrations.AddField(
            model_name='character',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='production.production'),
        ),
        migrations.AddField(
            model_name='crewassignment',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='production.production'),
        ),
        migrations.AddField(
            model_name='crewcall',
            name='call_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_calls', to='crew.callsheet'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewcall',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crew.crewmember'),
        ),
        migrations.AddField(
            model_name='crewassignment',
            name='crew_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crew.crewmember'),
        ),
        migrations.AddField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='crew.crewmember'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='crew.department'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='primary_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_crew', to='crew.position'),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='secondary_positions',
            field=models.ManyToManyField(blank=True, related_name='secondary_crew', to='crew.position'),
        ),
        migrations.AddField(
            model_name='crewassignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.position'),
        ),
        migrations.AlterUniqueTogether(
            name='callsheet',
            unique_together={('production', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='crewcall',
            unique_together={('call_sheet', 'crew_member')},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('production', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('title', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='crewassignment',
            unique_together={('production', 'crew_member', 'position')},
        ),
    ]
