# Generated by Django 5.2.3 on 2025-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('weather_dependent', models.BooleanField(default=False)),
                ('weather_backup_plan', models.TextField(blank=True)),
                ('crew_call', models.TimeField()),
                ('wrap_time', models.TimeField(blank=True, null=True)),
                ('estimated_wrap', models.TimeField()),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
                ('special_equipment', models.TextField(blank=True)),
                ('special_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_days', to='production.location')),
                ('primary_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_days', to='production.location')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooting_days', to='production.production')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('production', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_shot', models.TimeField(blank=True, null=True)),
                ('lunch_in', models.TimeField(blank=True, null=True)),
                ('lunch_out', models.TimeField(blank=True, null=True)),
                ('wrap_time', models.TimeField(blank=True, null=True)),
                ('total_setups', models.IntegerField(default=0)),
                ('pages_shot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scenes_completed', models.IntegerField(default=0)),
                ('delays', models.TextField(blank=True)),
                ('equipment_issues', models.TextField(blank=True)),
                ('weather_impact', models.TextField(blank=True)),
                ('tomorrow_prep_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.crewmember')),
                ('shooting_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_report', to='schedule.shootingday')),
            ],
        ),
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('sunrise_time', models.TimeField(blank=True, null=True)),
                ('sunset_time', models.TimeField(blank=True, null=True)),
                ('weather_forecast', models.CharField(blank=True, max_length=200)),
                ('temperature_high', models.IntegerField(blank=True, null=True)),
                ('temperature_low', models.IntegerField(blank=True, null=True)),
                ('nearest_hospital', models.CharField(blank=True, max_length=200)),
                ('hospital_phone', models.CharField(blank=True, max_length=20)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_director', models.BooleanField(default=False)),
                ('approved_by_producer', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.crewmember')),
                ('shooting_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_sheet', to='schedule.shootingday')),
            ],
        ),
        migrations.CreateModel(
            name='CrewCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.TimeField()),
                ('wardrobe_time', models.TimeField(blank=True, null=True)),
                ('makeup_time', models.TimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('call_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_calls', to='schedule.callsheet')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.location')),
            ],
            options={
                'ordering': ['call_time', 'crew_member__last_name'],
                'unique_together': {('call_sheet', 'crew_member')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_start_time', models.TimeField()),
                ('estimated_duration', models.DurationField()),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('setup_notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_days', to='production.scene')),
                ('shooting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scenes', to='schedule.shootingday')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('shooting_day', 'scene')},
            },
        ),
    ]
