# Generated by Django 5.2.4 on 2025-07-07 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_start', models.DateField()),
                ('prep_end', models.DateField()),
                ('principal_start', models.DateField()),
                ('principal_end', models.DateField()),
                ('wrap_date', models.DateField()),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('holidays', models.JSONField(blank=True, default=list)),
                ('blackout_dates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='production.production')),
            ],
        ),
        migrations.CreateModel(
            name='ShootingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shoot_date', models.DateField()),
                ('day_number', models.IntegerField()),
                ('general_call', models.TimeField()),
                ('shooting_call', models.TimeField()),
                ('estimated_wrap', models.TimeField(blank=True, null=True)),
                ('actual_wrap', models.TimeField(blank=True, null=True)),
                ('weather_forecast', models.CharField(blank=True, max_length=200)),
                ('sunrise', models.TimeField(blank=True, null=True)),
                ('sunset', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.location')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooting_days', to='production.production')),
            ],
            options={
                'ordering': ['shoot_date', 'day_number'],
                'unique_together': {('production', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('scene_moved', 'Scene Moved'), ('scene_added', 'Scene Added'), ('scene_removed', 'Scene Removed'), ('time_changed', 'Time Changed'), ('location_changed', 'Location Changed'), ('day_cancelled', 'Day Cancelled'), ('day_added', 'Day Added')], max_length=30)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_changes', to='production.production')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.scene')),
                ('shooting_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.shootingday')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DayBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('meal', 'Meal Break'), ('rest', 'Rest Break'), ('company_move', 'Company Move'), ('other', 'Other')], max_length=20)),
                ('scheduled_start', models.TimeField()),
                ('scheduled_duration', models.DurationField()),
                ('actual_start', models.TimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('shooting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedule.shootingday')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('day_start', 'Day Started'), ('first_shot', 'First Shot'), ('scene_complete', 'Scene Complete'), ('meal_break', 'Meal Break'), ('back_from_meal', 'Back from Meal'), ('company_move', 'Company Move'), ('weather_hold', 'Weather Hold'), ('wrap', "That's a Wrap"), ('general', 'General Update')], max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('scenes_completed', models.IntegerField(default=0)),
                ('setups_completed', models.IntegerField(default=0)),
                ('pages_shot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.scene')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_status_updates', to='production.production')),
                ('shooting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='schedule.shootingday')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SceneSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_order', models.IntegerField()),
                ('estimated_start', models.TimeField()),
                ('estimated_duration', models.DurationField()),
                ('actual_start', models.TimeField(blank=True, null=True)),
                ('actual_end', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('setup', 'Setting Up'), ('rehearsal', 'Rehearsing'), ('shooting', 'Shooting'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('setup_notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='production.scene')),
                ('shooting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_schedules', to='schedule.shootingday')),
            ],
            options={
                'ordering': ['shooting_day', 'day_order'],
                'unique_together': {('shooting_day', 'scene')},
            },
        ),
    ]
