# Generated by Django 5.2.4 on 2025-07-07 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('crew_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipment_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('catering_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_daily_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumulative_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('planned_daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_page', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_per_scene', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CrewPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('late_minutes', models.IntegerField(default=0)),
                ('punctuality_rating', models.IntegerField(default=5)),
                ('quality_rating', models.IntegerField(default=5)),
                ('teamwork_rating', models.IntegerField(default=5)),
                ('efficiency_rating', models.IntegerField(default=5)),
                ('tasks_assigned', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_wrap_time', models.TimeField(blank=True, null=True)),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scenes_scheduled', models.IntegerField(default=0)),
                ('scenes_completed', models.IntegerField(default=0)),
                ('pages_scheduled', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pages_shot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('setups_completed', models.IntegerField(default=0)),
                ('takes_total', models.IntegerField(default=0)),
                ('takes_good', models.IntegerField(default=0)),
                ('schedule_variance_minutes', models.IntegerField(default=0)),
                ('average_setup_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pages_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('crew_count', models.IntegerField(default=0)),
                ('crew_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('equipment_issues', models.IntegerField(default=0)),
                ('weather_delays_minutes', models.IntegerField(default=0)),
                ('technical_delays_minutes', models.IntegerField(default=0)),
                ('other_delays_minutes', models.IntegerField(default=0)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('velocity_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('milestone', 'Milestone Report')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_shooting_days', models.IntegerField(default=0)),
                ('total_scenes_shot', models.IntegerField(default=0)),
                ('total_pages_shot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_pages_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_on_schedule', models.IntegerField(default=0)),
                ('days_behind_schedule', models.IntegerField(default=0)),
                ('average_delay_minutes', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('equipment_issues_count', models.IntegerField(default=0)),
                ('weather_delay_days', models.IntegerField(default=0)),
                ('script_completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('schedule_completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('executive_summary', models.TextField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('next_period_forecast', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='VelocityTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_ending', models.DateField()),
                ('pages_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scenes_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('setups_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('velocity_trend', models.CharField(choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing')], default='stable', max_length=20)),
                ('projected_completion_date', models.DateField(blank=True, null=True)),
                ('days_ahead_behind', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_ending'],
            },
        ),
    ]
