# Generated by Django 5.2.3 on 2025-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0002_initial'),
        ('production', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('default_priority', models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal'), ('high', 'High Priority'), ('urgent', 'URGENT')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crew.department')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='production.production')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('production', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'General Message'), ('status_update', 'Status Update'), ('delay', 'Delay Notice'), ('emergency', 'Emergency'), ('meal', 'Meal Call'), ('wrap', 'Wrap Notice'), ('weather', 'Weather Update'), ('equipment', 'Equipment Issue'), ('cast_ready', 'Cast Ready'), ('moving_on', 'Moving On'), ('lunch', 'Lunch Break')], default='message', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'URGENT')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_scene', models.CharField(blank=True, max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('auto_trigger', models.CharField(blank=True, max_length=50)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='production.production')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='crew.crewmember')),
                ('shooting_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.shootingday')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationchannel')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_scene', models.CharField(blank=True, max_length=10)),
                ('current_shot', models.CharField(blank=True, max_length=10)),
                ('current_status', models.CharField(choices=[('prep', 'Preparing'), ('rehearsal', 'Rehearsing'), ('lighting', 'Lighting'), ('rolling', 'Rolling'), ('reset', 'Resetting'), ('moving_on', 'Moving On'), ('meal_break', 'Meal Break'), ('weather_hold', 'Weather Hold'), ('equipment_issue', 'Equipment Issue'), ('wrapped', 'Wrapped')], max_length=15)),
                ('estimated_next_shot', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('minutes_behind', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='production.production')),
                ('shooting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='schedule.shootingday')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rain', 'Rain Warning'), ('wind', 'High Wind'), ('temperature', 'Extreme Temperature'), ('storm', 'Storm Warning'), ('fog', 'Fog/Visibility')], max_length=12)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'URGENT')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('precipitation_chance', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('auto_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='production.production')),
                ('shooting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to='schedule.shootingday')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('walkie', 'Walkie-Talkie'), ('runner', 'Physical Runner')], default='app', max_length=10)),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.crewmember')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
            ],
            options={
                'unique_together': {('notification', 'crew_member')},
            },
        ),
    ]
